name: Github Actions Demo

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        - uses: actions/checkout@v3.3.0
        run: echo 'Hello World!'

      

